- src/app/rate/rate-main/rate-main.component.ts
- src/app/rate/rate-tariff/tariff.component.ts
whitespace issue in rate, tariff
> fixed whitespace issue in rate,tariff

- src/app/commons/components/application-data-table/application-data-table.component.html
- src/app/commons/components/application-data-table/application-data-table.component.ts
- src/app/commons/models/application-data-models.ts
- src/app/data-providers/approval-remote-data.service.ts
JIRA Issue Link : [https://jira.wso2telco.com/jira/browse/DEPAM-138](url)
Added API Name for subscription creation field and removed the ID filter.
Loads duplicate API Names in the Filter
> WIP adding API Name to approvals subscriptions

- src/app/commons/components/application-data-table/application-data-table.component.html
- src/app/commons/components/application-data-table/application-data-table.component.scss
- src/app/commons/components/application-data-table/application-data-table.component.ts
JIRA Issue Link : [ https://jira.wso2telco.com/jira/browse/DEPAM-135](url)
Made comment filed mandatory in Application and Subscription Reject process.
> Comment field mandatory in application/subscription reject

- src/app/rate/create/rate-main/rate-main.component.ts
- src/app/rate/create/rate-ratecategory/ratecategory.component.html
- src/app/rate/create/rate-ratecategory/ratecategory.component.ts
JIRA Issue Link : [https://jira.wso2telco.com/jira/browse/DEPAM-123](url)
Adding delete function to remove selected combination in Rate section
> DEPAM-123 adding delete function to remove combinations

- src/app/commons/components/application-data-table/application-data-table.component.html
- src/app/commons/components/application-data-table/application-data-table.component.ts
JIRA Issue Link : [https://jira.wso2telco.com/jira/browse/DEPAM-138](url)
Added the Api Name Filter to Application and Subscription Creation.
Removed the duplicates in Api Name Dropdown.
> apiName working filter added

- src/app/commons/components/responsive-table/responsive-table.component.html
- src/app/commons/components/responsive-table/responsive-table.component.scss
- src/app/commons/components/responsive-table/responsive-table.component.ts
- src/app/history/history-filter/history-filter.component.html
JIRA Issue Link [:](https://jira.wso2telco.com/jira/browse/DEPAM-108)
Removed the search button.
Display Message when filter returns no data
> history filter fixes

- src/app/rate/create/rate-main/rate-main.component.html
- src/app/rate/create/rate-main/rate-main.component.scss
- src/app/rate/create/rate-ratecategory/ratecategory.component.scss
- src/app/rate/view/view-rate-main.component.html
- src/app/rate/view/view-rate.component.scss
> Adding view rate card UI optimizations

- src/app/commons/components/application-data-table/application-data-table.component.html
- src/app/commons/components/application-data-table/application-data-table.component.scss
> workflow and application approval style changes

- src/app/rate/assign/assign-rate-main.component.html
- src/app/rate/assign/assign-rate.component.scss
- src/app/rate/rate.module.ts
> Showing Assigned rate for perticular API operation

- src/app/commons/components/application-data-table/application-data-table.component.html
- src/app/commons/components/application-data-table/application-data-table.component.ts
- src/app/commons/models/application-data-models.ts
- src/app/data-providers/approval-remote-data.service.ts
Fixed user filter in application and subscription pages.
> User filter Fix

- src/app/approvals/applications/applications.component.html
- src/app/approvals/subscriptions/subscriptions.component.html
- src/app/commons/components/application-data-table/application-data-table.component.ts
- src/app/dashboard/home/home.component.html
JIRA Issue Link [:](https://jira.wso2telco.com/jira/browse/DEPAM-157)
Adding warning messages to assign the task to you before editing
> approval subscription message

- src/app/commons/components/application-data-table/application-data-table.component.html
> fixed clear error field in comment section

- src/app/rate/create/rate-main/rate-main.component.scss
- src/app/rate/view/view-rate-main.component.html
> Adding table styles

- src/app/rate/view/view-rate-main.component.html
> Handling empty sub category status

- npm-shrinkwrap.json
- src/app/rate/assign/assign-rate-main.component.html
- src/app/rate/assign/assign-rate-main.component.ts
> Changing Assign rate button label

- src/app/commons/components/responsive-table/responsive-table.component.html
- src/app/commons/components/responsive-table/responsive-table.component.ts
- src/app/commons/models/reporing-data-models.ts
- src/app/data-providers/reporting-remote-data.service.ts
- src/app/history/application-detail/application-detail.component.html
- src/app/history/application-detail/application-detail.component.spec.ts
- src/app/history/application-detail/application-detail.component.ts
- src/app/history/history-main/history-main.component.ts
- src/app/history/history.module.ts
- src/app/history/history.routes.ts
JIRA Issue Link [:](https://jira.wso2telco.com/jira/browse/DEPAM-186)
Adding Application Name Link in the Approval History Page (New Manage App)
> Application History Link 

- server/private/modules/applications/application_assign_rest_service.js
- server/private/modules/applications/application_details_rest_service.js
- server/private/modules/applications/application_history_rest_service.js
- server/private/modules/applications/application_service.js
- server/private/modules/applications/application_task_complete_rest_service.js
- server/private/modules/applications/application_tasks_rest_service.js
- src/app/data-providers/approval-remote-data.service.ts
- src/app/data-providers/dashboard-remote-data.service.ts
- src/app/data-providers/reporting-remote-data.service.ts
> WIP basic auth workflow

- src/app/history/application-detail/application-detail.component.html
- src/app/history/application-detail/application-detail.component.scss
> Adding application detail page changes

- src/app/commons/components/application-data-table/application-data-table.component.ts
- src/app/commons/components/responsive-table/responsive-table.component.html
- src/app/history/history-main/history-main.component.ts
> minor UI text changes

- src/main/java/com/wso2telco/dep/manageservice/resource/service/rate/CategoryService.java
- src/main/java/com/wso2telco/dep/manageservice/resource/service/rate/CurrencyService.java
- src/main/java/com/wso2telco/dep/manageservice/resource/service/rate/RateCardService.java
- src/main/java/com/wso2telco/dep/manageservice/resource/service/rate/RateDefinitionService.java
- src/main/java/com/wso2telco/dep/manageservice/resource/service/rate/RateTypeService.java
- src/main/java/com/wso2telco/dep/manageservice/resource/service/rate/TariffService.java
- src/main/java/com/wso2telco/dep/manageservice/resource/service/rate/TaxService.java
- src/main/java/com/wso2telco/dep/manageservice/resource/service/workflow/ApplicationAssignService.java
- src/main/java/com/wso2telco/dep/manageservice/resource/service/workflow/ApplicationSearchService.java
- src/main/java/com/wso2telco/dep/manageservice/resource/service/workflow/ApproveSubscriptionService.java
- src/main/java/com/wso2telco/dep/manageservice/resource/service/workflow/HistoryService.java
- src/main/java/com/wso2telco/dep/manageservice/resource/util/Messages.java
> code modifications

- src/main/java/com/wso2telco/dep/manageservice/resource/model/rate/Category.java
- src/main/java/com/wso2telco/dep/manageservice/resource/model/rate/Currency.java
- src/main/java/com/wso2telco/dep/manageservice/resource/model/rate/RateCategory.java
- src/main/java/com/wso2telco/dep/manageservice/resource/model/rate/RateDefinition.java
- src/main/java/com/wso2telco/dep/manageservice/resource/model/rate/RateType.java
- src/main/java/com/wso2telco/dep/manageservice/resource/model/rate/Tariff.java
- src/main/java/com/wso2telco/dep/manageservice/resource/model/rate/Tax.java
- src/main/java/com/wso2telco/dep/manageservice/resource/resource/AbstractResource.java
- src/main/java/com/wso2telco/dep/manageservice/resource/resource/rate/CategoryResource.java
- src/main/java/com/wso2telco/dep/manageservice/resource/resource/rate/CurrencyResource.java
- src/main/java/com/wso2telco/dep/manageservice/resource/resource/rate/RateCardResource.java
- src/main/java/com/wso2telco/dep/manageservice/resource/service/ServiceFactory.java
- src/main/java/com/wso2telco/dep/manageservice/resource/service/rate/CategoryService.java
- src/main/java/com/wso2telco/dep/manageservice/resource/service/rate/CurrencyService.java
- src/main/java/com/wso2telco/dep/manageservice/resource/service/rate/RateCardService.java
- src/main/java/com/wso2telco/dep/manageservice/resource/service/rate/RateFactory.java
- src/main/java/com/wso2telco/dep/manageservice/resource/service/rate/RateService.java
- src/main/java/com/wso2telco/dep/manageservice/resource/service/rate/RateServiceI.java
- src/main/java/com/wso2telco/dep/manageservice/resource/util/ServiceTypes.java
> framework modified

- src/main/java/com/wso2telco/dep/manageservice/resource/resource/AbstractResource.java
- src/main/java/com/wso2telco/dep/manageservice/resource/resource/RequestTransferable.java
- src/main/java/com/wso2telco/dep/manageservice/resource/resource/quota/QuotaLimitResource.java
- src/main/java/com/wso2telco/dep/manageservice/resource/resource/rate/CategoryResource.java
- src/main/java/com/wso2telco/dep/manageservice/resource/resource/rate/CurrencyResource.java
- src/main/java/com/wso2telco/dep/manageservice/resource/resource/rate/RateCardResource.java
- src/main/java/com/wso2telco/dep/manageservice/resource/resource/rate/RateDefinitionResource.java
- src/main/java/com/wso2telco/dep/manageservice/resource/resource/rate/RateTypeResource.java
- src/main/java/com/wso2telco/dep/manageservice/resource/resource/rate/TariffResource.java
- src/main/java/com/wso2telco/dep/manageservice/resource/resource/rate/TaxResource.java
- src/main/java/com/wso2telco/dep/manageservice/resource/service/ServiceFactory.java
- src/main/java/com/wso2telco/dep/manageservice/resource/service/rate/CategoryService.java
- src/main/java/com/wso2telco/dep/manageservice/resource/service/rate/CurrencyService.java
- src/main/java/com/wso2telco/dep/manageservice/resource/service/rate/RateCardService.java
- src/main/java/com/wso2telco/dep/manageservice/resource/service/rate/RateDefinitionService.java
- src/main/java/com/wso2telco/dep/manageservice/resource/service/rate/RateFactory.java
- src/main/java/com/wso2telco/dep/manageservice/resource/service/rate/RateTypeService.java
- src/main/java/com/wso2telco/dep/manageservice/resource/service/rate/TariffService.java
- src/main/java/com/wso2telco/dep/manageservice/resource/service/rate/TaxService.java
- src/main/java/com/wso2telco/dep/manageservice/resource/util/ServiceTypes.java
JIRA Issue Link : https://jira.wso2telco.com/jira/browse/MA-12
> MA-12 complete

- src/app/quotacap/quotacap-main/quotacap-main.component.ts
> DEPAM-238 Quota cap doesn't validate according to the invalid field

- src/main/java/com/wso2telco/dep/manageservice/resource/model/rate/ApiOperation.java
- src/main/java/com/wso2telco/dep/manageservice/resource/model/rate/ApiOperationRates.java
- src/main/java/com/wso2telco/dep/manageservice/resource/resource/AbstractResource.java
- src/main/java/com/wso2telco/dep/manageservice/resource/resource/rate/ApiOperationRatesResource.java
- src/main/java/com/wso2telco/dep/manageservice/resource/resource/rate/ApiOperationsResource.java
- src/main/java/com/wso2telco/dep/manageservice/resource/resource/rate/AssignRateResource.java
- src/main/java/com/wso2telco/dep/manageservice/resource/service/ServiceFactory.java
- src/main/java/com/wso2telco/dep/manageservice/resource/service/Serviceable.java
- src/main/java/com/wso2telco/dep/manageservice/resource/service/quota/QuotaLimitService.java
- src/main/java/com/wso2telco/dep/manageservice/resource/service/rate/ApiOperationRatesService.java
- src/main/java/com/wso2telco/dep/manageservice/resource/service/rate/ApiOperationsService.java
- src/main/java/com/wso2telco/dep/manageservice/resource/service/rate/AssignRateService.java
- src/main/java/com/wso2telco/dep/manageservice/resource/service/rate/CategoryService.java
- src/main/java/com/wso2telco/dep/manageservice/resource/service/rate/CurrencyService.java
- src/main/java/com/wso2telco/dep/manageservice/resource/service/rate/RateCardService.java
- src/main/java/com/wso2telco/dep/manageservice/resource/service/rate/RateDefinitionService.java
- src/main/java/com/wso2telco/dep/manageservice/resource/service/rate/RateFactory.java
- src/main/java/com/wso2telco/dep/manageservice/resource/service/rate/TariffService.java
- src/main/java/com/wso2telco/dep/manageservice/resource/service/rate/TaxService.java
- src/main/java/com/wso2telco/dep/manageservice/resource/util/Messages.java
> Rate Assign Services

- src/app/quotacap/quotacap-main/quotacap-main.component.html
- src/app/rate/assign/assign-rate-main.component.html
- src/app/rate/create/rate-category/category.component.html
- src/app/rate/create/rate-currency/currency.component.html
- src/app/rate/create/rate-main/rate-main.component.html
- src/app/rate/create/rate-ratecategory/ratecategory.component.html
- src/app/rate/create/rate-tariff/tariff.component.html
- src/app/rate/view/view-rate-main.component.html
> Difficult to select an item from drop down due to drop down cache MA-26

- src/main/java/com/wso2telco/dep/manageservice/resource/resource/whitelist/SubscriberResource.java
- src/main/java/com/wso2telco/dep/manageservice/resource/service/ServiceFactory.java
- src/main/java/com/wso2telco/dep/manageservice/resource/service/whitelist/SubscriberService.java
- src/main/java/com/wso2telco/dep/manageservice/resource/service/whitelist/WhiteListFactory.java
- src/main/java/com/wso2telco/dep/manageservice/resource/util/Messages.java
- src/main/java/com/wso2telco/dep/manageservice/resource/util/ServiceTypes.java
- ui/src/app/commons/services/whitelist.service.ts
- ui/src/app/whitelist/whitelist-main/whitelist-main.component.ts
- WhiteList Initial Project Structure
- getSubscribers service
> whiteList init Services 

- src/main/java/com/wso2telco/dep/manageservice/resource/model/rate/AssignedRate.java
- src/main/java/com/wso2telco/dep/manageservice/resource/model/rate/Operator.java
- src/main/java/com/wso2telco/dep/manageservice/resource/resource/rate/OperatorResource.java
- src/main/java/com/wso2telco/dep/manageservice/resource/service/rate/OperatorService.java
- ui/src/app/commons/services/quotacap.service.ts
- ui/src/app/data-providers/quotacap_remote-data.service.ts
- ui/src/app/quotacap/quotacap-main/quotacap-main.component.ts
- ui/src/app/rate/assign/assign-rate-main.component.ts
> UI Changes

- ui/src/app/commons/services/quotacap.service.ts
- ui/src/app/commons/services/rate.service.ts
- ui/src/app/commons/services/whitelist.service.ts
- ui/src/app/data-providers/quotacap_remote-data.service.ts
- ui/src/app/data-providers/whitelist_remote-data.service.ts
- ui/src/app/quotacap/quotacap-main/quotacap-main.component.ts
- ui/src/app/rate/assign/assign-rate-main.component.ts
> quota cap fixed

- ui/src/app/commons/services/blacklist.service.ts
- ui/src/app/data-providers/blacklist_remote-data.service.ts
- ui/src/app/data-providers/dashboard-remote-data.service.ts
- ui/src/app/rate/assign/assign-rate-main.component.ts
> UI modifcations

- src/app/rate/create/rate-main/rate-main.component.scss
- src/app/rate/create/rate-tariff/tariff.component.html
- src/app/rate/create/rate-tariff/tariff.component.ts
> MA-39 Can creates a tariff without completing 100%

- src/app/rate/create/rate-tariff/tariff.component.html
- src/app/rate/create/rate-tariff/tariff.component.ts
>  MA38-Can't add minus values to the commission fields in tariff UI

- src/app/rate/create/rate-tariff/tariff.component.ts
> MA-51-It's better to remove zero values from tariff fields

- src/app/rate/view/view-rate-main.component.ts
> ui modifications

- server/private/config/application_config.js
- server/private/modules/applications/application_rest_service.js
- server/private/modules/applications/application_service.js
> Rc3 dev , not full functional

- src/app/commons/components/application-data-table/application-data-table.component.html
- src/app/commons/components/application-data-table/application-data-table.component.scss
> DEPAM-232 Rate Card Details widget is not clear

- server/private/modules/applications/application_rest_service.js
- server/private/modules/applications/application_service.js
> DEPAM-231 node service

- server/private/modules/applications/application_service.js
- server/private/modules/applications/application_task_complete_rest_service.js
- src/app/whitelist/whitelist-main/whitelist-main.component.ts
> Additional Logs Removed

- package.json
> 1.0.5 bundle

- src/main/java/com/wso2telco/dep/manageservice/resource/model/workflow/Task.java
- src/main/java/com/wso2telco/dep/manageservice/resource/resource/authentication/AuthenticationResource.java
- src/main/java/com/wso2telco/dep/manageservice/resource/resource/authentication/TempAuthResource.java
- ui/src/app/approvals/applications/applications.component.ts
- ui/src/app/approvals/approval-helper.service.ts
- ui/src/app/approvals/subscriptions/subscriptions.component.ts
- ui/src/app/commons/services/authentication.service.ts
- ui/src/app/dashboard/home/home.component.ts
- ui/src/app/data-providers/application-remote-data.service.ts
- ui/src/app/data-providers/approval-remote-data.service.ts
- ui/src/app/data-providers/dashboard-remote-data.service.ts
- ui/src/app/data-providers/login_remote-data.service.ts
>  UI changes for MA-6 MA-78 in-complete

- ui/src/app/quotacap/quotacap-main/quotacap-main.component.html
- ui/src/app/quotacap/quotacap-main/quotacap-main.component.ts
https://jira.wso2telco.com/jira/browse/MA-111
> MA-111 Quota assignment based on operator

- ui/angular-cli.json
- ui/src/app/app.routes.ts
- ui/src/app/approvals/applications/applications.component.html
- ui/src/app/approvals/applications/applications.component.ts
- ui/src/app/approvals/approval-helper.service.ts
- ui/src/app/approvals/subscriptions/subscriptions.component.html
- ui/src/app/commons/components/application-data-table/application-data-table.component.html
- ui/src/app/commons/components/application-data-table/application-data-table.component.ts
- ui/src/app/commons/components/main-menu/main-menu.component.ts
- ui/src/app/commons/components/responsive-table/responsive-table.component.html
- ui/src/app/commons/components/responsive-table/responsive-table.component.scss
- ui/src/app/commons/components/responsive-table/responsive-table.component.ts
- ui/src/app/commons/components/subscription-data-table/subscription-data-table.component.html
- ui/src/app/commons/components/subscription-data-table/subscription-data-table.component.ts
- ui/src/app/commons/models/common-data-models.ts
- ui/src/app/commons/models/reporing-data-models.ts
- ui/src/app/commons/services/authentication.service.ts
- ui/src/app/commons/services/rate.service.ts
- ui/src/app/data-providers/rate_remote-data.service.ts
- ui/src/app/data-providers/reporting-remote-data.service.ts
- ui/src/app/history/history-main/history-main.component.html
- ui/src/app/history/history-main/history-main.component.ts
- ui/src/app/rate/assign/assign-rate-main.component.ts
- ui/src/app/rate/create/rate-ratecategory/ratecategory.component.html
- ui/src/app/rate/create/rate-ratecategory/ratecategory.component.ts
- ui/src/app/rate/create/rate-tariff/tariff.component.ts
- ui/src/app/rate/view/view-rate-main.component.html
- ui/src/app/rate/view/view-rate-main.component.ts
>  MA-121,  MA-120

- .gitignore
- ui/angular-cli.json
- ui/src/app/commons/components/application-data-table/application-data-table.component.html
- ui/src/app/commons/components/application-data-table/application-data-table.component.scss
- ui/src/app/commons/components/responsive-table/responsive-table.component.html
- ui/src/app/commons/components/responsive-table/responsive-table.component.scss
- ui/src/app/commons/components/subscription-data-table/subscription-data-table.component.html
- ui/src/app/commons/components/subscription-data-table/subscription-data-table.component.scss
https://jira.wso2telco.com/jira/browse/MA-122
> [MA-122] Applying UI modification for Filters

- ui/src/app/commons/models/common-data-models.ts
- ui/src/app/rate/create/rate-main/rate-main.component.html
- ui/src/app/rate/create/rate-main/rate-main.component.ts
https://jira.wso2telco.com/jira/browse/MA-118
> MA-118 show Tax description in create rate-card screen

- ui/npm-shrinkwrap.json
- ui/package.json
- ui/src/app/app.routes.ts
- ui/src/app/commons/components/main-menu/main-menu.component.ts
- ui/src/app/operatoronboarding/operatoronboarding-main/operatoronboarding.component.html
- ui/src/app/operatoronboarding/operatoronboarding-main/operatoronboarding.component.scss
- ui/src/app/operatoronboarding/operatoronboarding-main/operatoronboarding.component.ts
- ui/src/app/operatoronboarding/operatoronboarding.module.ts
- ui/src/app/operatoronboarding/operatoronboarding.routes.ts
- ui/src/app/quotacap/quotacap-main/quotacap-main.component.ts
JIRA Issue Link 
https://jira.wso2telco.com/jira/browse/MA-129
https://jira.wso2telco.com/jira/browse/MA-130
https://jira.wso2telco.com/jira/browse/MA-131
Operator onboarding UI implementation
Mobile Country Codes (MCC) and Mobile Network Codes (MNC) service layer implementation
>  MA-129 - Operator onboarding UI implementation

- ui/src/app/operatoronboarding/add/add-main/operatoronboarding.component.html
- ui/src/app/operatoronboarding/add/add-main/operatoronboarding.component.scss
- ui/src/app/operatoronboarding/add/add-main/operatoronboarding.component.ts
- ui/src/app/operatoronboarding/add/add-token/token.component.html
- ui/src/app/operatoronboarding/add/add-token/token.component.scss
- ui/src/app/operatoronboarding/add/add-token/token.component.ts
- ui/src/app/operatoronboarding/operatoronboarding.module.ts
- ui/src/app/operatoronboarding/operatoronboarding.routes.ts
https://jira.wso2telco.com/jira/browse/MA-126
> MA-126 UI for Manage the Operator endpoint through single application

- ui/src/app/app.module.ts
- ui/src/app/commons/components/common-data-table/common-data-table.component.html
- ui/src/app/commons/components/common-data-table/common-data-table.component.scss
- ui/src/app/commons/components/common-data-table/common-data-table.component.spec.ts
- ui/src/app/commons/components/common-data-table/common-data-table.component.ts
- ui/src/app/commons/components/main-menu/main-menu.component.ts
- ui/src/app/commons/models/common-data-models.ts
- ui/src/app/commons/models/operator-onboarding-data-models.ts
- ui/src/app/config/api.endpoints.ts
- ui/src/app/data-providers/operator-onboarding-data.service.spec.ts
- ui/src/app/data-providers/operator-onboarding-data.service.ts
- ui/src/app/operatoronboarding/view-operators/view-operators.component.html
- ui/src/app/operatoronboarding/view-operators/view-operators.component.scss
- ui/src/app/operatoronboarding/view-operators/view-operators.component.ts
- ui/src/app/shared/shared.module.ts
- ui/src/assets/json/get.operators.json
> MA-124 add view to show added operators

- ui/src/app/app.mock.backend.ts
- ui/src/app/app.module.ts
- ui/src/app/commons/components/breadcrumbs/breadcrumbs.component.ts
- ui/src/app/commons/models/common-data-models.ts
- ui/src/app/commons/models/operator-onboarding-data-models.ts
- ui/src/app/config/api.endpoints.ts
- ui/src/app/data-providers/operator-onboarding-data.service.ts
- ui/src/app/operatoronboarding/create-operator-endpoint/add-endpoint-form/add-endpoint-form.component.html
- ui/src/app/operatoronboarding/create-operator-endpoint/add-endpoint-form/add-endpoint-form.component.scss
- ui/src/app/operatoronboarding/create-operator-endpoint/add-endpoint-form/add-endpoint-form.component.spec.ts
- ui/src/app/operatoronboarding/create-operator-endpoint/add-endpoint-form/add-endpoint-form.component.ts
- ui/src/app/operatoronboarding/create-operator-endpoint/create-operator-endpoint.component.html
- ui/src/app/operatoronboarding/create-operator-endpoint/create-operator-endpoint.component.scss
- ui/src/app/operatoronboarding/create-operator-endpoint/create-operator-endpoint.component.spec.ts
- ui/src/app/operatoronboarding/create-operator-endpoint/create-operator-endpoint.component.ts
- ui/src/app/operatoronboarding/operatoronboarding.module.ts
- ui/src/app/operatoronboarding/operatoronboarding.routes.ts
- ui/src/app/operatoronboarding/view-operators/view-operators.component.html
- ui/src/app/operatoronboarding/view-operators/view-operators.component.ts
- ui/src/assets/json/get.operators.json
> MA-128  Operator endpoint defining process UI

- component/ui/angular-cli.json
- component/ui/src/app/commons/models/operator-onboarding-data-models.ts
- component/ui/src/app/operatoronboarding/add/add-main/operatoronboarding.component.html
- component/ui/src/app/operatoronboarding/add/add-main/operatoronboarding.component.ts
- component/ui/src/app/operatoronboarding/add/add-token/token.component.html
- component/ui/src/app/operatoronboarding/add/add-token/token.component.ts
- component/ui/src/app/operatoronboarding/operatoronboarding.module.ts
- component/ui/src/app/operatoronboarding/operatoronboarding.routes.ts
- component/ui/src/app/operatoronboarding/view-operators/view-operators.component.html
- component/ui/src/app/operatoronboarding/view-operators/view-operators.component.ts
- ui/package-lock.json
> MA-136 Binding token assign section with View operator section

- component/ui/src/app/operatoronboarding/add/add-token/token.component.html
- component/ui/src/app/operatoronboarding/add/add-token/token.component.ts
https://jira.wso2telco.com/jira/browse/MA-138
> Token forms validation/ bug fixing

- component/manage-ui/src/app/login/user-login/user-login.component.html
- component/manage-ui/src/app/login/user-login/user-login.component.scss
https://jira.wso2telco.com/jira/browse/MA-141
> MA-141 Login page UI modification

- component/manage-ui/src/app/quotacap/quotacap-main/quotacap-main.component.ts
> DEPAM-370 Doesn't show Quota values for selected filters

- component/manage-ui/src/app/quotacap/quotacap-main/quotacap-main.component.ts
https://jira.wso2telco.com/jira/browse/DEPAM-375
> DEPAM-375 Modification for Operator based quota assign

- component/manage-ui/src/app/commons/components/application-data-table/application-data-table.component.html
- component/manage-ui/src/app/commons/components/application-data-table/application-data-table.component.scss
- component/manage-ui/src/app/commons/components/subscription-data-table/subscription-data-table.component.scss
https://jira.wso2telco.com/jira/browse/HUBDEV-1996
> HUBDEV-1996 Rate Card Details widget is not clear

- component/manage-ui/src/app/commons/models/common-data-models.ts
- component/manage-ui/src/app/rate/create/rate-tariff/tariff.component.html
- component/manage-ui/src/app/rate/create/rate-tariff/tariff.component.ts
- component/manage-ui/src/app/subscriptions/subscription-detail/update-sub.component.html
- component/manage-ui/src/app/subscriptions/subscription-detail/update-sub.component.scss
- component/manage-ui/src/app/subscriptions/subscription-detail/update-sub.component.ts
https://jira.wso2telco.com/jira/browse/HUBDEV-1997
https://jira.wso2telco.com/jira/browse/HUBDEV-2008
>  HUBDEV-2008 /  HUBDEV-1997 Northbound pricing fail in payment API

- component/manage-ui/src/app/quotacap/quotacap-main/quotacap-main.component.ts
https://jira.wso2telco.com/jira/browse/HUBDEV-2013
> HUBDEV-2013 Change quota-cap service layer according to new parameter

- component/manage-ui/src/app/quotacap/quotacap-main/quotacap-main.component.ts
https://jira.wso2telco.com/jira/browse/DEPAM-421
> DEPAM-421 - Modify payload of quota-cap service call

- .gitignore
- component/manage-ui/src/app/app.http.interceptor.ts
- component/manage-ui/src/app/app.module.ts
- component/manage-ui/src/app/commons/commons.module.ts
- component/manage-ui/src/app/commons/services/timer.service.ts
JIRA Issue Link : https://jira.wso2telco.com/jira/browse/DEPAM-433
> DEPAM-433 add idle session timeout

- component/manage-service/src/main/java/com/wso2telco/dep/manageservice/resource/service/authentication/AuthenticationService.java
- component/manage-ui/src/app/commons/models/common-data-models.ts
- component/manage-ui/src/app/commons/services/authentication.service.ts
- component/manage-ui/src/app/commons/services/rate.service.ts
- component/manage-ui/src/app/data-providers/rate_remote-data.service.ts
- component/manage-ui/src/app/quotacap/quotacap-main/quotacap-main.component.ts
- component/manage-ui/src/app/rate/view/view-rate-main.component.ts
- component/manage-ui/src/app/subscriptions/subscription-detail/update-sub.component.ts
Introducing operator name attribute to the user profile
Fixes for showing all rate for operator
Fix for showing all rate cards for operator subscription
> Introducing operator name attribute to the user profile

- component/manage-service/src/main/java/com/wso2telco/dep/manageservice/resource/service/validation/MsisdnValidationService.java
- component/manage-service/src/main/java/com/wso2telco/dep/manageservice/resource/util/ApplicationConfiguration.java
…
https://jira.wso2telco.com/jira/browse/HUBDEV-2091
> Fix for HUBDEV-2091 - Read msisdn validation service url from api-manager.xml

- component/ui/src/app/commons/components/application-data-table/application-data-table.component.html
- component/ui/src/app/commons/components/application-data-table/application-data-table.component.scss
- component/ui/src/app/commons/components/subscription-data-table/subscription-data-table.component.scss
> Adding low resoultion style

- component/manage-ui/src/app/commons/models/common-data-models.ts
- component/manage-ui/src/app/commons/services/rate.service.ts
- component/manage-ui/src/app/data-providers/rate_remote-data.service.ts
- component/manage-ui/src/app/rate/create/rate-main/rate-main.component.ts
- component/manage-ui/src/app/rate/create/rate-tax/tax.component.html
- component/manage-ui/src/app/rate/create/rate-tax/tax.component.ts
https://jira.wso2telco.com/jira/browse/HUBDEV-2146
https://jira.wso2telco.com/jira/browse/HUBDEV-2252
Capable of Applying tax on tax for a rate card.
On the fly Tax creation for a rate card
> Tax generating user interface / front-end service creation for tax on tax scenario

- component/manage-ui/src/app/blacklist/apiwise/apiblacklist-main/apiblacklist-main.component.ts
- component/manage-ui/src/app/whitelist/whitelist-main/whitelist-main.component.ts
Fixes for HUBDEV-2280 and MA-88
> HUBDEV-2280 The Error information message doesn't disappear

- component/manage-ui/angular-cli.json
- component/manage-ui/package.json
- component/manage-ui/src/app/rate/create/rate-main/rate-main.component.ts
- component/manage-ui/src/app/rate/create/rate-tax/tax.component.html
- component/manage-ui/src/app/rate/create/rate-tax/tax.component.ts
[DEPORGHUB-93]
[DEPORGHUB-94] 
[HUBDEV-2305]
> Tax on Tax Feature - Bug Fixes

- component/manage-ui/src/app/login/user-login/user-login.component.html
JIRA Issue Link : https://jira.wso2telco.com/jira/browse/INTGW-438
Removing Forget Password Option from Manage service portal
> INTGW-438 Removing Forget Password Option from Manage service portal

- component/manage-ui/src/app/login/user-login/user-login.component.html
- component/manage-ui/src/app/login/user-login/user-login.component.ts
[https://jira.wso2telco.com/jira/browse/INTGW-414]
updating the year
> INTGW-414 updating the year

- component/manage-ui/src/app/commons/components/application-data-table/application-data-table.component.ts
- component/manage-ui/src/app/commons/components/subscription-data-table/subscription-data-table.component.ts
- component/manage-ui/src/app/history/application-history-table/application-history-table.component.ts
JIRA Issue Link : https://jira.wso2telco.com/jira/browse/INTGW-408
This modification removes spaces in the search string using Javascript
https://localhost:9443/manage-service
> INTGW-408 Filter Modification on manage-services

- component/manage-ui/src/app/commons/components/application-data-table/application-data-table.component.html
- component/manage-ui/src/app/commons/components/responsive-table/responsive-table.component.html
- component/manage-ui/src/app/commons/components/subscription-data-table/subscription-data-table.component.html
- component/manage-ui/src/app/commons/models/application-data-models.ts
- component/manage-ui/src/app/history/application-history-table/application-history-table.component.html
JIRA Issue Link : https://jira.wso2telco.com/jira/browse/INTGW-436
Filter search with spaces done
> INTGW-436  Filter function is not working and INTGW-507 Table header 'DATE' is missing in application approval UI in manage-services

- component/manage-ui/src/app/commons/components/application-data-table/application-data-table.component.html
JIRA Issue Link : https://jira.wso2telco.com/jira/browse/INTGW-507
> INTGW-507 Table header name change

- component/manage-ui/src/app/history/application-history-table/application-history-table.component.html
JIRA Issue Link : https://jira.wso2telco.com/jira/browse/INTGW-411 https://jira.wso2telco.com/jira/browse/INTGW-410
Removing column 'Approved By' in History table
> INTGW-411/410 Removing column 'Approved By' in History table

- component/manage-ui/src/app/data-providers/reporting-remote-data.service.ts
- component/manage-ui/src/app/history/application-detail/application-detail.component.html
- component/manage-ui/src/app/history/application-detail/application-detail.component.ts
- component/manage-ui/src/app/history/application-history-table/application-history-table.component.html
- component/manage-ui/src/app/history/application-history-table/application-history-table.component.ts
https://jira.wso2telco.com/jira/browse/INTGW-412
> INTGW-412 Application History Details (more) Page depending on Deployment type 

- component/manage-ui/src/app/history/history-main/history-main.component.html
- component/manage-ui/src/app/history/history-main/history-main.component.ts
- component/manage-ui/src/app/history/subscription-history-table/subscription-history-table.component.html
JIRA Issue Link : https://jira.wso2telco.com/jira/browse/INTGW-435
application view permission added
filter change
> INTGW 435 - changes from review

- component/manage-ui/src/app/commons/components/subscription-data-table/subscription-data-table.component.html
- component/manage-ui/src/app/history/application-history-table/application-history-table.component.html
alignment issue in the tooltip
> [Code Review Request] - [INTGW] - Tooltip Fix

- component/manage-ui/package.json
- component/manage-ui/src/app/blacklist/apiwise/apiblacklist-list/apiblacklist-list.component.html
- component/manage-ui/src/app/blacklist/apiwise/apiblacklist-list/apiblacklist-list.component.ts
- component/manage-ui/src/app/blacklist/apiwise/apiblacklist-main/apiblacklist-main.component.html
- component/manage-ui/src/app/blacklist/apiwise/apiblacklist-main/apiblacklist-main.component.scss
- component/manage-ui/src/app/blacklist/apiwise/apiblacklist-main/apiblacklist-main.component.ts
- component/manage-ui/src/app/blacklist/blacklist.module.ts
- component/manage-ui/src/app/commons/commons.module.ts
- component/manage-ui/src/app/commons/services/blacklist_whitelist.service.ts
- component/manage-ui/src/app/data-providers/blacklist_whitelist_remote-data.service.ts
- component/manage-ui/src/app/whitelist/whilelist-list/whitelist-list.component.html
- component/manage-ui/src/app/whitelist/whilelist-list/whitelist-list.component.ts
- component/manage-ui/src/app/whitelist/whitelist-main/whitelist-main.component.html
- component/manage-ui/src/app/whitelist/whitelist-main/whitelist-main.component.scss
- component/manage-ui/src/app/whitelist/whitelist-main/whitelist-main.component.ts
- component/manage-ui/src/app/whitelist/whitelist.module.ts
[EXTGW-384](https://jira.wso2telco.com/jira/browse/EXTGW-384?filter=-1)
[EXTGW-391](https://jira.wso2telco.com/jira/browse/EXTGW-391?filter=-1)
[EXTGW-389](https://jira.wso2telco.com/jira/browse/EXTGW-389?filter=-1)
Revamp blacklist msisdn search feature 
Feature development for Download blacklist number list for particular API
UI for bulk number blacklist and frontend validation
> Adding blacklist/whitelist new features

- README.md
- component/manage-ui/src/app/blacklist/apiwise/apiblacklist-main/apiblacklist-main.component.html
- component/manage-ui/src/app/blacklist/apiwise/apiblacklist-main/apiblacklist-main.component.ts
- component/manage-ui/src/app/commons/components/main-menu/main-menu.component.ts
- component/manage-ui/src/app/whitelist/whitelist-main/whitelist-main.component.html
- component/manage-ui/src/app/whitelist/whitelist-main/whitelist-main.component.ts
>  Remove hard coded menu item and Resetting blacklisted number count when invalid filter applies

- component/manage-ui/src/app/approvals/approval-helper.service.ts
- component/manage-ui/src/app/commons/models/application-data-models.ts
- component/manage-ui/src/app/commons/models/common-data-models.ts
- component/manage-ui/src/app/commons/services/blacklist_whitelist.service.ts
- component/manage-ui/src/app/commons/services/rate.service.ts
- component/manage-ui/src/app/data-providers/approval-remote-data.service.ts
- component/manage-ui/src/app/data-providers/blacklist_whitelist_remote-data.service.ts
- component/manage-ui/src/app/data-providers/rate_remote-data.service.ts
- component/manage-ui/src/app/subscriptions/edit-subscription.module.ts
- component/manage-ui/src/app/subscriptions/edit-subscription.routes.ts
- component/manage-ui/src/app/subscriptions/edit-subscription/subscription-detail.component.html
- component/manage-ui/src/app/subscriptions/edit-subscription/subscription-detail.component.scss
- component/manage-ui/src/app/subscriptions/edit-subscription/subscription-detail.component.ts
- component/manage-ui/src/app/subscriptions/subscription-detail/update-sub.component.html
- component/manage-ui/src/app/subscriptions/subscription-detail/update-sub.component.ts
> Feature for Edit subscription tier and Application tier

- component/manage-ui/src/app/app.routes.ts
- component/manage-ui/src/app/commons/components/main-menu/main-menu.component.ts
- component/manage-ui/src/app/subscriptions/edit-subscription/subscription-detail.component.scss
- component/manage-ui/src/app/subscriptions/edit-subscription/subscription-detail.component.ts
- component/manage-ui/src/app/subscriptions/subscription-detail/update-sub.component.html
- component/manage-ui/src/app/subscriptions/subscription-detail/update-sub.component.ts
> Update edit subscription routing and menu item name

- component/manage-ui/src/app/app.component.scss
- component/manage-ui/src/app/subscriptions/edit-subscription/subscription-detail.component.html
- component/manage-ui/src/app/subscriptions/edit-subscription/subscription-detail.component.scss
> INTGW-917 [410][manage-service]- UI enhacements

- component/manage-ui/src/app/app.routes.ts
- component/manage-ui/src/app/commons/components/main-menu/main-menu.component.ts
- component/manage-ui/src/app/subscriptions/edit-subscription/subscription-detail.component.html
- component/manage-ui/src/app/subscriptions/edit-subscription/subscription-detail.component.ts
- component/manage-ui/src/app/subscriptions/subscription-detail/update-sub.component.html
https://jira.wso2telco.com/jira/browse/INTGW-916
https://jira.wso2telco.com/jira/browse/INTGW-1037 It should not allow the publisher to change the application tier
> INTGW-916 INTGW-1037 [410][manage-service]- Better to restrict view for admin and publishers

- component/manage-ui/angular-cli.json
- component/manage-ui/package.json
- component/manage-ui/src/app/app.routes.ts
- component/manage-ui/src/app/commons/components/main-menu/main-menu.component.ts
- component/manage-ui/src/app/subscriptions/edit-subscription/subscription-detail.component.html
- component/manage-ui/src/app/subscriptions/edit-subscription/subscription-detail.component.ts
- component/manage-ui/src/app/subscriptions/subscription-detail/update-sub.component.html
https://jira.wso2telco.com/jira/browse/INTGW-1054
Remove edit-rate feature from the internal gateway
> INTGW-1054 [410][manage-service]- Publisher is not loading in the fields of EDIT-SUBSCRIPTION-APPLICATION page 'operator'

- pom.xml
Updated core.version to match with compatible core-util pom version
> updated core.version
